### ISSUE TITLE
Replace config-files in project settings with profiles

### ISSUE THREAD

**Issue by buvoli** [container-job-runner/cjr#61]
For a multistack project, it is not very useful to have a single array of configuration files in project-settings since it affects all the stacks. This functionality should be replaced with the concept of profiles, with a default profile that is always selected. 

Proposed YML would be:
```
profiles:
  default:
  - config_file_1
  - config_file_2
  special: 
  - config_file_3
```

A Job could then be run using
`cjr $ COMMAND --profile=PROFILENAME`
